name: Static Analysis

on:
  push:
    branches: [main]
  workflow_dispatch: 
  
jobs:
  check-styles:
    name: Lint & Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.33.0
      - name: Install & Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.22.1'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Prettier
        run: pnpm prettier:format
        
